apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: test-lvmcluster
  namespace: openshift-storage
spec:
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/router
    operator: Exists
  storage:
    deviceClasses:
    - name: vg1
      fstype: xfs 
      default: true
      nodeSelector: 
        nodeSelectorTerms:
        - matchExpressions:
          - key: mykey
            operator: In
            values:
            - ssd
      deviceSelector: 
        paths:
        - /dev/disk/by-path/pci-0000:00:01.1-ata-2.1
      thinPoolConfig:
        name: thin-pool-1
        sizePercent: 90 
        overprovisionRatio: 10
        chunkSize: 128Ki 
        chunkSizeCalculationPolicy: Static 
