apiVersion: v1
kind: Secret
metadata:
  name: 3par-secret
  namespace: hpe-csi-driver
stringData:
  serviceName: primera3par-csp-svc
  servicePort: "8080"
  backend: 60.30.160.212
  username: 3parcloud
  password: 3parcloud
