apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
  name: web-root-disk
  namespace: test
spec:
  pvc:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
    storageClassName: px-rwx-block-kubevirt
  source:
    http:
      url: http://172.1.157.214:8080/vm-images/ubuntu-22.04.qcow2

