apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sriov-network-operator-subscription
  namespace: openshift-sriov-network-operator
spec:
  channel: "stable"
  installPlanApproval: "Manual"
  name: sriov-network-operator
  source: redhat-operator-sriov-network-operator-index
  sourceNamespace: openshift-marketplace
