apiVersion: sriovnetwork.openshift.io/v1
kind: SriovOperatorConfig
metadata:
  name: default 
  namespace: openshift-sriov-network-operator
spec:
  configDaemonNodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  disableDrain: false
  enableInjector: true
  enableOperatorWebhook: true
  logLevel: 0
