apiVersion: nmstate.io/v1beta1 
kind: NodeNetworkConfigurationPolicy 
metadata: 
  name: csdb-bond0-351-vlan-policy 
spec: 
  nodeSelector: 
    node-role.kubernetes.io/worker: "" 
  desiredState: 
    interfaces: 
    - name: bond0.351 
      description: VLAN using bond0 
      type: vlan 
      state: up 
      vlan: 
        base-iface: bond0 
        id: 351
