apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pod-pv-0
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: test-sc
  local:
    path: /var/lib/containers/test-pod-pv-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - skt-bssocpdawkr01.devocp1-416.sktelecom.com
          - skt-bssocpdawkr02.devocp1-416.sktelecom.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pod-pv-1
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: test-sc
  local:
    path: /var/lib/containers/test-pod-pv-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - skt-bssocpdawkr01.devocp1-416.sktelecom.com
          - skt-bssocpdawkr02.devocp1-416.sktelecom.com
