apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: test-nncp
spec:
  desiredState:
    interfaces:
      - bridge:
          options:
            stp:
              enabled: false
          port:
            - name: ens9
        name: br0
        state: up
        type: linux-bridge
        ipv4:
          enabled: false
  nodeSelector:
    node-role.kubernetes.io/infra: ""
