---
- name: Set Kernel Parameters
  hosts: new_workers
  become: yes  # This allows Ansible to run commands as sudo

  tasks:
    - name: Set kernel arguments
      command: grubby --update-kernel=ALL --args="default_hugepagesz=2M hugepagesz=2M transparent_hugepage=never intel_idle.max_cstate=0 processor.max_cstate=1 intel_iommu=on iommu=pt skew_tick=1 intel_pstate=disable nosoftlockup module_blacklist=irdma"

    - name: Create hugepages-2M.service file
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=HugeTLB Gigantic Pages Reservation
          DefaultDependencies=no
          Before=dev-hugepages.mount
          ConditionPathExists=/sys/devices/system/node
          ConditionKernelCommandLine=hugepagesz=2M

          [Service]
          Type=oneshot
          RemainAfterExit=yes
          ExecStart=/usr/lib/systemd/hugepages-2M.sh

          [Install]
          WantedBy=sysinit.target
        dest: /usr/lib/systemd/system/hugepages-2M.service
        mode: '0755'

    - name: Create hugepages-2M.sh script
      ansible.builtin.copy:
        content: |
          #!/bin/sh

          nodes_path=/sys/devices/system/node/
          if [ ! -d $nodes_path ]; then
              echo "ERROR: $nodes_path does not exist"
              exit 1
          fi

          reserve_pages()
          {
              echo $1 > $nodes_path/$2/hugepages/hugepages-2048kB/nr_hugepages
          }

          reserve_pages 12000 node0
          reserve_pages 12000 node1
        dest: /usr/lib/systemd/hugepages-2M.sh
        mode: '0755'

    - name: Enable hugepages-2M service
      ansible.builtin.systemd:
        name: hugepages-2M
        enabled: yes
        state: started

    - name: Reboot the server
      ansible.builtin.reboot:
        reboot_timeout: 300
      async: 0
      poll: 0
      ignore_errors: yes

    - name: Wait for server to come up
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: 22  # SSH port
        state: started
        timeout: 600
      delegate_to: localhost

