apiVersion: velero.io/v1
kind: Backup
metadata:
  name: test-backup
  labels:
    velero.io/storage-location: default
  namespace: openshift-adp
spec:
  includedNamespaces:
  - test-oadp
  storageLocation: test-dpa-1
  defaultVolumesToFsBackup: true
  ttl: 72h0m0s 
