apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scc-privileged
  namespace: test-oadp
rules:
- apiGroups:
  - security.openshift.io
  resourceName:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scc-privileged
  namespace: test-oadp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scc-privileged
subjects:
- kind: ServiceAccount
  name: default
  namespace: test-oadp

