apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: metallb-operator-sub
  namespace: metallb-system
spec:
  channel: "stable"
  installPlanApproval: "Manual"
  name: metallb-operator
  source: metallb-operator-index
  sourceNamespace: openshift-marketplace
