apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test01-admin
  namespace: openshift-cnv
subjects:
- kind: User
  name: test01
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
