apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-wal-pv-2
spec:
  capacity:
    storage: 150Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: test-logging-sc
  local:
    path: /var/lib/containers/test-wal-pv-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - skt-bssocpdawkr01.devocp1-416.sktelecom.com
          - skt-bssocpdawkr02.devocp1-416.sktelecom.com
---
