apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-master-chrony-conf
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,c2VydmVyIDE3Mi4zMS4yNTIuNTYgaWJ1cnN0CnNlcnZlciAxNzIuMzEuMjUyLjU3IGlidXJzdApzZXJ2ZXIgMTcyLjMxLjI1Mi41OCBpYnVyc3QKc2VydmVyIDE3Mi4zMS4yNTIuNTkgaWJ1cnN0CmRyaWZ0ZmlsZSAvdmFyL2xpYi9jaHJvbnkvZHJpZnQKbWFrZXN0ZXAgMS4wIDMKcnRjc3luYwpsb2dkaXIgL3Zhci9sb2cvY2hyb255Cg==
          mode: 420
          overwrite: true
          path: /etc/chrony.conf
