apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: custom-mss512-tuned-profile
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=Setting tuning parameters
      include=openshift-node
      [variables]
      isolated_cores=2-27,30-55,58-83,86-111
      no_balance_cores=2-27,30-55,58-83,86-111
      isolated_cores_assert_check = \\${isolated_cores}
      assert1=${f:assertion_non_equal:isolated_cores are set:${isolated_cores}:${isolated_cores_assert_check}}
      tmpdir=${f:strip:${f:exec:mktemp:-d}}
      isolated_cores_expanded=${f:cpulist_unpack:${isolated_cores}}
      isolated_cpumask=${f:cpulist2hex:${isolated_cores_expanded}}
      not_isolated_cores_expanded=${f:cpulist_invert:${isolated_cores_expanded}}
      isolated_cores_online_expanded=${f:cpulist_online:${isolated_cores}}
      not_isolated_cores_online_expanded=${f:cpulist_online:${not_isolated_cores_expanded}}
      not_isolated_cpumask=${f:cpulist2hex:${not_isolated_cores_expanded}}
      no_balance_cores_expanded=${f:cpulist_unpack:${no_balance_cores}}
      assert2=${f:assertion:isolated_cores contains online CPU(s):${isolated_cores_expanded}:${isolated_cores_online_expanded}}
      [sysctl]
      kernel.hung_task_timeout_secs = 600
      kernel.nmi_watchdog = 0
      kernel.sched_rt_runtime_us = -1
      kernel.timer_migration = 0
      kernel.numa_balancing=0
      net.core.busy_read=50
      net.core.busy_poll=50
      net.ipv4.tcp_fastopen=3
      vm.stat_interval = 10
      kernel.sched_min_granularity_ns=10000000
      vm.dirty_ratio=10
      vm.dirty_background_ratio=3
      vm.swappiness=10
      kernel.sched_migration_cost_ns=5000000
      net.ipv4.tcp_keepalive_time = 600
      net.ipv4.tcp_keepalive_intvl = 75
      net.ipv4.tcp_keepalive_probes = 9
      net.ipv4.tcp_retries1 = 3
      net.ipv4.tcp_retries2 = 5
      net.ipv4.tcp_syn_retries = 2
      net.ipv4.tcp_synack_retries = 5
      net.ipv4.tcp_congestion_control = cubic
      net.ipv4.tcp_fin_timeout = 30
      net.ipv4.tcp_window_scaling = 1
      [sysfs]
      /sys/bus/workqueue/devices/writeback/cpumask = ${not_isolated_cpumask}
      /sys/devices/virtual/workqueue/cpumask = ${not_isolated_cpumask}
      /sys/devices/virtual/workqueue/*/cpumask = ${not_isolated_cpumask}
      /sys/devices/system/machinecheck/machinecheck*/ignore_ce = 1
      [cpu]
      force_latency=cstate.id:1|3
      governor=performance
      energy_perf_bias=performance
      min_perf_pct=100
      [vm]
      transparent_hugepages=never
      [systemd]
      cpu_affinity=${not_isolated_cores_expanded}
      [irqbalance]
      banned_cpus=""
      [script]
      priority=5
      script=/usr/lib/tuned/cpu-partitioning/script.sh      
      [scheduler]
      runtime=0
      group.ksoftirqd=0:f:11:*:ksoftirqd.*
      group.rcuc=0:f:11:*:rcuc.*
      sched_rt_runtime_us=-1
      sched_min_granularity_ns=10000000
      sched_migration_cost_ns=5000000
      numa_balancing=0
      default_irq_smp_affinity = ignore
      isolated_cores=${isolated_cores}
      ps_blacklist=.*pmd.*;.*PMD.*;^DPDK;.*qemu-kvm.*;^contrail-vroute$;^lcore-slave-.*;^rte_mp_handle$;^rte_mp_async$;^eal-intr-thread$
      sched_wakeup_granularity_ns = 4000000
      [selinux]
      avc_cache_threshold=8192
      [net]
      nf_conntrack_hashsize=131072
    name: custom-mss512-tuned-profile
  recommend:
  - machineConfigLabels:
      machineconfiguration.openshift.io/role: mss512
    priority: 20
    profile: custom-mss512-tuned-profile

