apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hostpath-sc
provisioner: kubevirt.io.hostpath-provisioner
reclaimPolicy: Delete 
volumeBindingMode: WaitForFirstConsumer 
parameters:
  storagePool: local-pool
