apiVersion: v1
kind: Secret
metadata:
  name: rhel9-test-vm-network
  namespace: test-vm
type: Opaque
stringData:
  networkData: |
    version: 2
    ethernets:
      eth0:
        dhcp4: false
        dhcp6: false
        addresses:
          - 172.1.157.20/24
        routes:
          - to: 0.0.0.0/0
            via: 172.1.157.1
