apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test-rhel9-vm-2
  namespace: test
spec:
  runStrategy: Always
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: rootdisk-dv
      spec:
        source:
          pvc:
            name: rhel-9.6-qcow2-dv
            namespace: test-images
        storage:
          resources:
            requests:
              storage: 35Gi
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: datadisk-dv
      spec:
        source:
          blank: {}
        storage:
          resources:
            requests:
              storage: 20Gi
  template:
    spec:
      domain:
        devices:
          disks:
            - name: rootdisk
              disk: { bus: virtio }
            - name: cloudinitdisk
              disk: { bus: virtio }
            - name: datadisk
              disk: { bus: virtio }
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 2Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: rootdisk-dv
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: cloud-user
              password: "dhvktm#01"
              chpasswd: { expire: False }
        - name: datadisk
          dataVolume:
            name: datadisk-dv
      tolerations:
        - key: node-role.kubernetes.io/infra
          operator: Exists
          effect: NoSchedule

