apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test-rhel8-vm-cpu8
  namespace: test
spec:
  runStrategy: Always
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: test-dv-cpu8
      spec:
        source:
          pvc:
            name: rhel-8.10-qcow2-dv
            namespace: test
        storage:
          resources:
            requests:
              storage: 35Gi
  template:
    spec:
      domain:
        cpu:
          cores: 8
          sockets: 1
          threads: 1
        devices:
          disks:
            - name: rootdisk
              disk: { bus: virtio }
            - name: cloudinitdisk
              disk: { bus: virtio }
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 2Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: test-dv-cpu8
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: cloud-user
              password: 'dhvktm#01'
              chpasswd: { expire: False }
      tolerations:
        - key: node-role.kubernetes.io/infra
          operator: Exists
          effect: NoSchedule

