apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: test
  labels:
    machineconfiguration.openshift.io/role: test
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,test]}
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/test: ""
