apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-hostpath-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: test-sc
  hostPath:
    path: /var/lib/containers/test-hostpath-pv
