apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    user: "ns-false-4.12"
  name: cluster-resources-admin
rules:
- apiGroups:
  - ""
  resources:
  - componentstatuses
  - namespaces
  - nodes
  - persistentvolumes
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - '*'
- apiGroups:
  - apiserver.openshift.io
  resources:
  - apirequestcounts
  verbs:
  - '*'
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - '*'
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectaccessreviews
  - selfsubjectrulesreviews
  - subjectaccessreviews
  verbs:
  - '*'
- apiGroups:
  - authorization.openshift.io
  resources:
  - clusterrolebindings
  - clusterroles
  - resourceaccessreviews
  - subjectaccessreviews
  verbs:
  - '*'
- apiGroups:
  - autoscaling.openshift.io
  resources:
  - clusterautoscalers
  verbs:
  - '*'
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - '*'
- apiGroups:
  - config.openshift.io
  resources:
  - apiservers
  - authentications
  - builds
  - clusteroperators
  - clusterversions
  - consoles
  - dnses
  - featuregates
  - imagecontentpolicies
  - images
  - infrastructures
  - ingresses
  - networks
  - nodes
  - oauths
  - operatorhubs
  - projects
  - proxies
  - schedulers
  verbs:
  - '*'
- apiGroups:
  - console.openshift.io
  resources:
  - consoleclidownloads
  - consoleexternalloglinks
  - consolelinks
  - consolenotifications
  - consoleplugins
  - consolequickstarts
  - consoleyamlsamples
  verbs:
  - '*'
- apiGroups:
  - flowcontrol.apiserver.k8s.io
  resources:
  - flowschemas
  - prioritylevelconfigurations
  verbs:
  - '*'
- apiGroups:
  - helm.openshift.io
  resources:
  - helmchartrepositories
  verbs:
  - '*'
- apiGroups:
  - image.openshift.io
  resources:
  - images
  - imagesignatures
  verbs:
  - '*'
- apiGroups:
  - imageregistry.operator.openshift.io
  resources:
  - configs
  - imagepruners
  verbs:
  - '*'
- apiGroups:
  - k8s.ovn.org
  resources:
  - egressips
  verbs:
  - '*'
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - containerruntimeconfigs
  - controllerconfigs
  - kubeletconfigs
  - machineconfigpools
  - machineconfigs
  verbs:
  - '*'
- apiGroups:
  - metal3.io
  resources:
  - provisionings
  verbs:
  - '*'
- apiGroups:
  - metrics.k8s.io
  resources:
  - nodes
  verbs:
  - '*'
- apiGroups:
  - migration.k8s.io
  resources:
  - storagestates
  - storageversionmigrations
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - '*'
- apiGroups:
  - node.k8s.io
  resources:
  - runtimeclasses
  verbs:
  - '*'
- apiGroups:
  - oauth.openshift.io
  resources:
  - oauthaccesstokens
  - oauthauthorizetokens
  - oauthclientauthorizations
  - oauthclients
  - tokenreviews
  - useroauthaccesstokens
  verbs:
  - '*'
- apiGroups:
  - operator.openshift.io
  resources:
  - authentications
  - cloudcredentials
  - clustercsidrivers
  - configs
  - consoles
  - csisnapshotcontrollers
  - dnses
  - etcds
  - imagecontentsourcepolicies
  - insightsoperators
  - kubeapiservers
  - kubecontrollermanagers
  - kubeschedulers
  - kubestorageversionmigrators
  - networks
  - openshiftapiservers
  - openshiftcontrollermanagers
  - servicecas
  - storages
  verbs:
  - '*'
- apiGroups:
  - operators.coreos.com
  resources:
  - olmconfigs
  - operators
  verbs:
  - '*'
- apiGroups:
  - performance.openshift.io
  resources:
  - performanceprofiles
  verbs:
  - '*'
- apiGroups:
  - project.openshift.io
  resources:
  - projectrequests
  - projects
  verbs:
  - '*'
- apiGroups:
  - quota.openshift.io
  resources:
  - clusterresourcequotas
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - '*'
- apiGroups:
  - samples.operator.openshift.io
  resources:
  - configs
  verbs:
  - '*'
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - '*'
- apiGroups:
  - security.internal.openshift.io
  resources:
  - rangeallocations
  verbs:
  - '*'
- apiGroups:
  - security.openshift.io
  resources:
  - rangeallocations
  - securitycontextconstraints
  verbs:
  - '*'
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotclasses
  - volumesnapshotcontents
  verbs:
  - '*'
- apiGroups:
  - storage.k8s.io
  resources:
  - csidrivers
  - csinodes
  - storageclasses
  - volumeattachments
  verbs:
  - '*'
- apiGroups:
  - template.openshift.io
  resources:
  - brokertemplateinstances
  verbs:
  - '*'
- apiGroups:
  - user.openshift.io
  resources:
  - groups
  - identities
  - useridentitymappings
  - users
  verbs:
  - '*'
