apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: skt:cluster-viewer-user
  labels:
    user: viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-viewer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: viewer
