apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-product
  namespace: openshift-distributed-tracing
spec:
  channel: stable
  installPlanApproval: Manual
  source: redhat-operator-index-0
  sourceNamespace: openshift-marketplace
  name: jaeger-product
