apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kiali-ossm
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Manual
  source: redhat-operator-index-0
  sourceNamespace: openshift-marketplace
  name: kiali-ossm
