apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
  namespace: openshift-operators
spec:
  channel: "1.0"
  installPlanApproval: Manual
  source: redhat-operator-index-0
  sourceNamespace: openshift-marketplace
  name: servicemeshoperator 
